config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:"tasks#index"
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :create]
  
  resources :tasks, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :status, presence: true, length: { maximum: 10 }
  validates :content, presence: true, length: { maximum: 255 }
  
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
  include SessionsHelper
  include Pagy::Backend
  
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
    end
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
    @pagy,@tasks = pagy(Task.all)
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      flash[:success] = 'task が正常に投稿されました'
      redirect_to @task
    else
      flash.now[:danger] = 'task が投稿されませんでした'
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      flash[:success] = 'Message は正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger] = 'task は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    flash[:success] = 'task は正常に削除されました'
    redirect_to tasks_url
  end
  
  private
  
  def task_params
    params.require(:task).permit(:content,:status)
  
  end
end
#aaabbb#qqq

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |task_type, task| %>
  <div class="alert alert-<%= task_type %>"><%= task %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">Tasklist</a>
      <!-- 横幅が狭い時に出るハンバーガーボタン -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- メニュー項目 -->
      <!--<div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">-->
      <!--  <ul class="navbar-nav">-->
      <!--    <li class="nav-item"><%= link_to  '新規メッセージの投稿', new_task_path, class: 'nav-link' %></li>-->
      <!--    <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>-->
      <!--    <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>-->
      <!--  </ul>-->
      <!--</div>-->
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
  <% if logged_in? %>
    <div class="btn-group">
      <ul class="navbar-nav">
        <li class="ms-3"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
      </ul>
      <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.name %></button>
      <ul class="dropdown-menu dropdown-menu-end">
        <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user), class: 'nav-link' %></li>
        <li class="dropdown-divider"></li>
        <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %></li>
      </ul>
    </div>
  <% else %>
    <ul class="navbar-nav">
      <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
    </ul>
  <% end %>
</div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |f| %>

<% if task.errors.any? %>
    <div id="error_explanation">
      <ul class="mb-0">
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="mb-3">
 <%= f.label :status, 'ステータス' %>
  <%= f.text_field :status %>
</div>

<div class="mb-3">
  <%= f.label :content, 'タスク' %>
  <%= f.text_field :content %>
</div>

  <%= f.submit '投稿', class: 'btn btn-primary' %>
<% end %>

<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %> のタスク編集ページ</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<% if @tasks.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>ステータス</th>
        <th>タスク</th>
      </tr>
    </thead>

<!--<ul>-->
<tbody>
  <% @tasks.each do |task| %>
    <!--<li><%= link_to task.id,task %> :<%= task.status %> &gt; <%= task.content %></li> -->
    <tr>
          <td><%= link_to task.id, task %></td>
          <td><%= task.status %></td>
          <td><%= task.content %></td>
        </tr>
      <% end %>
</tbody>
</table>
    
 

<div>
<%== pagy_bootstrap_nav(@pagy) %>
</div>
 <% end %>

<%= link_to '新規タスクの作成', new_task_path ,class: "btn btn-primary" %>

<% if logged_in? %>
  <p>ログイン完了ユーザ: <%= current_user.name %></p>
<% else %>
  <div class="bg-secondary p-3 p-sm-5 my-4 rounded">
    <div class="text-center text-white">
      <h1>Welcome to the Microposts</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/tasks/new.html.erb
<!--<h1>タスク新規作成ページ</h1> 

<%= render 'form', task: @task %> -->

app/views/tasks/show.html.erb
<h1>id: <%= @task.id%>　のタスク詳細ページ</h1>

<!--<p>ステータス<%= @task.status %></p>
<p>タスク<%= @task.content %></p>

<%= link_to '一覧に戻る', tasks_path %>
<%= link_to 'このタスクを編集する', edit_task_path(@task) %>
<%= link_to 'このタスクを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %> -->

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <td><%= @task.id %></td>
  </tr>
  <tr>
    <th>タイトル</th>
    <td><%= @task.status %></td>
  </tr>
  <tr>
    <th>メッセージ</th>
    <td><%= @task.content %></td>
  </tr>
</table>

<%= link_to 'このタスクを編集する', edit_task_path(@task), class: 'btn btn-light' %>
<%= link_to 'このタスクを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>